name: Deploy EKS Cluster

on:
  push:
    branches:
      - main
    paths:
      - 'modules/eks/**'
      - '.github/workflows/eks_deployment.yml'

jobs:
  deploy-eks:
    name: Deploy EKS Cluster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-west-2"  # Replace with your AWS region

    - name: Terraform Init
      run: terraform -chdir=modules/eks init -backend-config="backend.hcl"

    - name: Terraform Plan
      run: terraform -chdir=modules/eks plan

    - name: Terraform Apply
      run: terraform -chdir=modules/eks apply -auto-approve
